// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:21793e62-ed68-4750-a17b-55d0143a1231",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_CFVuj4MA2",
    "aws_user_pools_web_client_id": "7pjnob763dc33i52hrcsbbmbjl",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://izy7wbymm5.execute-api.us-east-2.amazonaws.com/devenv",
            "region": "us-east-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://pr2r5mh7sjgozfhad7sdj5touy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4edhrdmyebeznptuoiotb2jifq"
};


export default awsmobile;
